# Generated by Django 4.2.7 on 2023-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EricaOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups')], default='grams', max_length=5),
        ),
    ]
