# Generated by Django 4.2.7 on 2023-11-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EricaOne', '0004_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='aliases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
