# Generated by Django 4.2.7 on 2023-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EricaOne', '0005_alter_dish_aliases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='prep_time',
        ),
        migrations.AddField(
            model_name='dish',
            name='prep_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='prep_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
