# Generated by Django 4.2.7 on 2023-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EricaOne', '0006_alter_dish_options_remove_dish_prep_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='EricaOne.category'),
        ),
    ]
