# Generated by Django 4.2.7 on 2023-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EricaOne', '0007_category_dish_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='dish_images/'),
        ),
    ]
